Repository RedHatInsights/insights-host-inventory, pull requests merged in 2025-02, with the labels that each got.

#2217 refactor(RHINENG-9816): clarify endpoint descriptions
  swagger/api.spec.yaml
  swagger/openapi.dev.json
  swagger/openapi.json
Labels: small, ready for review

#2221 refactor(RHINENG-14063): improve org_id check
  lib/check_org.py
  tests/test_api_hosts_get.py
Labels: ready for review

#2228 fix(RHINENG-5484): fix logic for multiple os names
  api/filtering/db_custom_filters.py
  tests/test_api_hosts_get.py
Labels: small, ready for review

#2123 [RHINENG-7833] - Send notification newly-stale hosts
  Dockerfile
  api/filtering/db_filters.py
  app/instrumentation.py
  app/models.py
  deploy/clowdapp.yml
  dev.dockerfile
  dev.yml
  generate_stale_host_notifications.py
  host_reaper.py
  jobs/__init__.py
  jobs/common.py
  lib/host_repository.py
  lib/metrics.py
  migrations/versions/4f0b36e6cf28_create_metadata_table_to_store_host_.py
  tests/helpers/mq_utils.py
  tests/test_custom_staleness.py
  tests/test_notifications.py
Labels: ready for review

#2240 (RHINENG-12028): serialize_host refactoring
  app/serialization.py
  lib/staleness.py
Labels: technical debts

#2277 RHINENG-15965: Add GH Actions to Dependabot
  .github/dependabot.yml
Labels: GitHub-Actions-Updates

#2285 [RHINENG-16082]: Update System Profile Schema
  swagger/openapi.dev.json
  swagger/openapi.json
  swagger/system_profile.spec.yaml
  swagger/system_profile_commit_id
Labels: system_profile_update
